# Styles
sass:
  sass_dir: _sass
  style: :compressed

# Site settings
title: eugene-sy.github.io
email: eugene.sypachev@gmail.com
description: 'Eugene Sypachev (@eugene-sy) Github page and blog.'
baseurl: ''
url: 'eugene-sy.github.io'
username: 'Eugene Sypachev'
twitter_username: axblade
github_username: eugene-sy

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
git: 'https://github.com/eugene-sy'
stackoverflow: 'http://stackoverflow.com/users/3205447/axblade'
linkedin: 'https://www.linkedin.com/pub/eugene-sypachev/50/780/ab2'

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - 'README.md'
  - 'CHANGELOG.md'
  - 'Gemfile'
  - 'Gemfile.lock'

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
